// Exemple de structure pour 2 pays, à compléter pour les 16
window.countries = [
{
    name: "Bénin",
    flag: "image/Bénin1.png",
    photo: "image/Bénin2.jpeg",
    capital: "Porto-Novo",
    capitaleconomy: "Cotonou",
    capitalPhoto: "image/Bénin3.jpeg",
    indépendence: "1er août 1960",
    population: "12 millions d'habitants",
    languages: ["Français", "Fon","Yorouba","Adja"],
    monuments: ["Palais Royal d'Abomey", "Cathédrale de Porto-Novo", "Ganvié"],
    monumentPhoto:"",
    culture: "Fort mélange de traditions vaudou, musique, cérémonies ancestrales, artisanat riche.",
    gastronomy: "Akassa, pâte rouge, yovo doko, Akumè, poisson fumé.",
    music: "Musique traditionnelle, musique moderne (Zinli, Afrobeat), chants rituels, influences afro-funk modernes.",
    economy: "Agriculture, pêche, tourisme, commerce portuaire",
    politics: "République avec vie politique active, alternance et reformes démocratiques en cours.",
    funfact: "Berceau historique du vaudou, Ganvié est surnommé la 'Venise de l'Afrique' pour ses maisons sur pilotis."
},
{
    name: "Burkina Faso",
    flag: "image/Burkina1.png",
    photo: "image/Burkina2.jpeg",
    capital: "Ouagadougou",
    capitalPhoto: "image/Burkina3.jpeg",
    independence: "5 août 1960",
    population: "21 millions d'habitants ",
    languages: ["Français", "Mooré", "Dioula", "Fula" ],
    monuments: ["Monument des Martyrs", "Sites culturels de Ouagadougou", "Sculptures de Laongo"],
    monumentPhoto:"",
    culture: "Forte tradition de festivals (cinéma FESPACO), artisanat, danses et contes oraux.",
    gastronomy: "Riz gras, to, sauces locales à base d'arachide et de légumes",
    music: "Musique traditionnelle et contemporaine, chants et percussions, scène locale très active.",
    economy: "Agriculture(mil, fonio), orpaillage, petit industrie et commerce informel.",
    politics: "Histoire de transitions politiques; société civile influente mais défis de gouvernance",
    funfact: "Ouagadougou accueille l'un des plus grands festivals de cinéma d'Afrique (FESPACO)." 
},
{
    name: "Cap-Vert",
    flag: "image/cap1.png",
    photo: "image/cap2.jpeg",
    capital: "Praia",
    capitalPhoto: "image/cap3.jpeg",
    independence: "5 juillet 1975",
    population: "0.55 million d'habitants",
    languages: ["Portugais", "Kriolu (créole)" ],
    monuments: ["Ciade Velha (site historique)", "Phare de Ponta do Sol", "Fortes coloniaux"],
    monumentPhoto:"",
    culture: "Mélange lusophone et africain ; forte tradition diasporique et musicale ",
    gastronomy: "Capucha (plat national), poissons et fruits de mer, influences portugaises.",
    music: "Morna, coladeira, funanà, musiques mélancoliques et dansantes. ",
    economy: "Tourisme, pêche, envois de fonds (diaspora), petite industrie.",
    politics: "Démocratie multipartite stable; relations avec pays lusophones.",
    funfact: "Archipel volcanique : chaque île a sa propre identité culturelle et musicale."
},
{
    name: "Côte d'Ivoire",
    flag: "image/abidjan1.png",
    photo: "image/abidjan2.jpeg",
    capital: "Yamoussoukro",
    capitaleconomy: "Abidjan",
    capitalPhoto: "image/abidjan3.jpeg",
    independence: "7 août 1960",
    population: "27 millions d'habitants ",
    languages: ["Français", "Baoulé", "Dioula"],
    monuments: ["Basilique Notre-Dame de la Paix", "Parc national de Taï", "Plateau d'Abidjan"],
    monumentPhoto:"",
    culture: "Riche vie urbaine,masques, grandes fêtes, tradition artisanal et danses traditionnelles.",
    gastronomy: "Attiéké, alloco, garba, plats à base de poisson et d'igname",
    music: "Coupé-décalé, zouglou, musiques populaires contemporaines ",
    economy: "Leader mondiale du cacao, café, pétrole, agriculture, port d'Abidjan",
    politics: "République présidentielle ; pays influent en Afrique de l'ouest",
    funfact: "La plus grande basilique du monde se trouve à Yamoussoukro."
},
{
    name: "Gambie",
    flag: "image/gambie1.jpeg",
    photo: "image/gambie2.jpeg",
    capital: "Bandjul",
    capitalPhoto: "image/gambie3.jpeg",
    independence: "18 février 1965",
    population: "2.4 millions d'habitants ",
    languages: ["Anglais", "Mandinka","Wolof", "Fula" ],
    monuments: ["Archipel et réserves naturelles", "Banjul (marchésssss et bâtiments coloniaux)"],
    monumentPhoto:"",
    culture: "Culture fluviale liée au fleuve Gambie, musique et artisanat locaux ",
    gastronomy: "Plats à base de poisson, riz, sauces locales (domoda)",
    music: "Musique traditionnelle (Kora, percussions) et chants locaux. ",
    economy: "Agriculture de subsistance, pêche, tourisme côtier.",
    politics: "Petite république avec histoire politique marquée par des transitions; gouvernance locale très importante.",
    funfact: "La Gambie est un pays très étroit, entouré presque entièrement par le Sénégal."
},
{
    name: "Ghana",
    flag: "image/gh1.png",
    photo: "image/gh2.jpeg",
    capital: "Accra",
    capitalPhoto: "image/gh3.jpeg",
    independence: "6 mars 1957",
    population: "32 millions d'habitants ",
    languages: ["Anglais", "Akan", "Twi", "Ga", "Ewe"],
    monuments: ["Château d'Elmina", "Kwame Nkrumah Mausoleum", "Cape Coast Castle"],
    monumentPhoto:"",
    culture: "Tissage du Kente, festivals traditionnels, coutumes Akan, forts côtiers historiques.  ",
    gastronomy: "Jollof rice, banku, fufu, soupes épicées à la viande et au poisson.",
    music: "Highlife, Afrobeats, scène musicale très inflente en Afrique.",
    economy: "Cacao, or, pétrole",
    politics: "République présidentielle; démocratie stable relative; acteur régionale important en Afrique de l'Ouest.",
    funfact: "Premier pays africain indépendant au XXe siècle."
},
{
    name: "Guinée",
    flag: "image/gu1.png",
    photo: "image/gu2.jpeg",
    capital: "Conakry",
    capitalPhoto: "image/gub3.jpeg",
    independence: "2 octobre 1958",
    population: "13 millions d'habitants",
    languages: ["Français", "Soussou", "Poular", "Maninka" ],
    monuments: ["Îles de Loos", "Monuments coloniaux de Conakry", "Sites culturels traditionnels"],
    monumentPhoto:"",
    culture: "Tradition madingue riche, musique (Kora), rites et artisanat.",
    gastronomy: "Poulat yassa et plats locaux, plats à base de riz et de sauces.",
    music: "Musique madingue, percussions et chants traditionnels.",
    economy: "Ressources minières, agriculture, pêche, tourisme.",
    politics: "Hiistoire politique marquée par des périodes d'instablité",
    funfact: "la Guinée possède d'importantes réserves de bauxite, minerai d'aluminium."
},
{
    name: "Guinée-Bissau",
    flag: "image/gub1.png",
    photo: "image/gub2.jpeg",
    capital: "Bissau",
    capitalPhoto: "image/gub3.jpeg",
    independence: "24septembre 1973",
    population: "2 millions d'habitants",
    languages: ["Portugais", "Crioulo", "Langues locales"],
    monuments: ["Îles Bijagòs (biodiversité)", "Sites historiques coloniaux à Bissau"],
    monumentPhoto:"",
    culture: "Mélange lusophone et africain, tradiditions animistes et musique Gumbé",
    gastronomy: "Plats de pêche, caldeirada, plats locaux",
    music: "Gumbé, musique traditionnelle et chant de danse",
    economy: "Agriculture, pêche, tourisme, économie modeste",
    politics: "Instabilités politique ponctuelles; gouvernance et développement sont des défis",
    funfact: "les îles Bijagòs sont reconnues pour leur biodiversité marine et culturelle ."
},
{
    name: "Libéria",
    flag: "image/lib1.png",
    photo: "image/lib2.jpeg",
    capital: "Monrovia",
    capitalPhoto: "image/lib3.jpeg",
    independence: "26 juillet 1847",
    population: "5 millios d'habitants ",
    languages: ["Anglais", "Languages autochtones diverses" ],
    monuments: ["Plages et fôrets tropicles", "sites historiques de Monrovia"],
    monumentPhoto:"",
    culture: "Influences afro-américaines mélangées aux cultures locales, musique et foi forte",
    gastronomy: "Plats à base de riz, sauces et poissons, soupes locales. ",
    music: "Gospel et traditions orales, musiques locales. ",
    economy: "Agriculture, exploitation forestère, ressources naturelles; reconstruction économique post-conflit.",
    politics: "Histoire marquée par conflitd et reconstruction ; démocratie en consolidation.",
    funfact: "Le Libéria a été fondé par d'anciens esclaves afro-américains au 19 siècle."
},
{
    name: "Mali",
    flag: "image/mali1.png",
    photo: "image/mali2.jpeg",
    capital: "Bamako",
    capitalPhoto: "image/mali3.jpeg",
    independence: "22 septembre 1960",
    population: "20 millions d'habitants",
    languages: ["Français", "Bambara", "Songhay", "Tamasheq"],
    monuments: ["Grande Mosquée de Djenné", "Timbuktu(sites historiques)", "Mosquées en terre crue"],
    monumentPhoto:"",
    culture: "Forte tradition mandingue : musique(griots), artisanat, littérature orale.Pl",
    gastronomy: "Plats de mil, riz, sauces de légumes et de viandes, spécialités locales. ",
    music: "Musique mandingue(Kora), artistes renommés de musique traditionnelle et mderne. ",
    economy: "Agriculture, élevage, défis de sécurité affectant l'économie",
    politics: "Problèmes sécuritaires au nord ; transitions poliriques et enjeux de gouvernance.",
    funfact: "Timbuktu était autrefois un important centre intellectuel et commercial transsaharien."
},
{
    name: "Mauritanie",
    flag: "image/mau1.png",
    photo: "image/mau2.jpeg",
    capital: "Nouakchott",
    capitalPhoto: "image/mau3.jpeg",
    independence: "28 novembre 1960",
    population: "4.5 millions d'habitants",
    languages: ["Arabe", "Français(largement utilisé)", "Langues locales berbères et africaines" ],
    monuments: ["Sites sahéliens, anciens forts, zones historiques nomades."],
    monumentPhoto:"",
    culture: "Mélange arabo-berbère et africain ; traditions nomades et musique sahélien.",
    gastronomy: "Plats de poisson, viand grillée (mechoui), influences sahariennes.",
    music: "Desert blues, musiques traditionnelles nomades.",
    economy: "Exploitation minière, pêche, élevage, économie sahélienne avec défis climatiques.",
    politics: "Pays sahélien avec enjeux sécuritaires et politiques régionnaux.",
    funfact: "La Mauritanie est une nation sahélienne avec une culture nomade riche."
},
{
    name: "Niger",
    flag: "image/nig1.png",
    photo: "image/nig2.jpeg",
    capital: "Niamey",
    capitalPhoto: "image/nig3.jpeg",
    independence: "3 août 1960",
    population: "25 millions d'habitants",
    languages: ["Français", "Haussa", "Zarma (Djerma)" ],
    monuments: ["Dunes et oasis sahariennes", "Sites culturels locaux"],
    monumentPhoto:"",
    culture: "Sociétés sahéliennes, traditions nomades, artisanat pastoral.",
    gastronomy: "Plats à base de mil et de céréales, sauces et viandes locales.",
    music: "Mélodies nomades et musique traditionnelle sahélienne",
    economy: "Agricuture de subsistance, uranium (ressource importante), élévage.",
    politics: "Pays sahélien confronté à des enjeux climatiques et sécuritaires; gouvernance en évolution.",
    funfact: "Le Niger possède d'importantes réserves d'uranium qui alimentent une part de l'industrie mondiale."
},
{
    name: "Nigeria",
    flag: "image/nige1.png",
    photo: "image/nige2.jpeg",
    capital: "Abuja",
    capitalPhoto: "image/nige3.jpeg",
    independence: "1er octobre 1960",
    population: "220 millions d'habitants",
    languages: ["Anglais", "Haussa", "Yoruba", "Igbo", "Plusieurs centaines dee langues locales" ],
    monuments: ["Zuma Rock", "Site national d'Olumo", "Mosquées et marchés historiques"],
    monumentPhoto:"",
    culture: "Extrêmement diverse (plus de 250 groupes ethniques), littérature, mode.",
    gastronomy: "Jollof rice, pounded yam, soupes épicées, variétés régionales riches.",
    music: "Afrobeats, highlife, juju, fuji ; scène musicale africaine dominante.",
    economy: "Plus grande économie d'Afrique ; pétrole, gaz, agriculture, industries créatives (Nollywood). ",
    politics: "Puissance régionnale ; défis politiques, sécurité et gouvernance à grande échelle.",
    funfact: "Le Nigéria est le pays le plus peuplé d'Afrique et possède une industrie cinématographique massive."
},
{
    name: "Sénégal",
    flag: "image/sen1.png",
    photo:"image/sen3.jpeg",
    capital: "Dakar",
    capitalPhoto: "image/sen2.jpeg",
    independence: "4 avril 1960",
    population: "18 millios d'habitants",
    languages: ["Français", "Wolof", "Pulaar", "Serer"],
    monuments: ["Île de Gorée", "Monument de la Renaissance africaine", "Lac Rose (Retba)"],
    monumentPhoto:"",
    culture: "Riche patrimoine littéraire et musical,le mbalax, la teranga, festivals.",
    gastronomy: "Thiéboudienne, yassa, plats épicés et variés.",
    music: "Scène musicale internationale, mbalax, musique populaire sénégalaise",
    economy: "Agriculture, pêche, tourisme, phosphate, éconmie diversifiéeen croissance.",
    politics: "République semi-présidentielle ; acteur démocratique régional ; scène politique et culturelle dynamique.",
    funfact: "L'Île de Gorée est un site historique majeur lié à la mémoire de la traite transatlantique."
  },
  {
    name: "Sierra Leone",
    flag: "image/sier1.png",
    photo: "image/sier2.jpeg",
    capital: "Freetown",
    capitalPhoto: "image/sier4.jpeg",
    independence: "27 avril 1961",
    population: "8 millions d'habitants",
    languages: ["Anglais", "Krio", "Langues locales" ],
    monuments: ["Sites histriques de Freetown", "Îles et plages autour de Freetown"],
    monumentPhoto:"",
    culture: "Traditions variées, histoire liée à la diaspora, musique et danse locales.",
    gastronomy: "Plats de poisson, groundnut stew (ragoût d'arachide), riz et sauces.",
    music: "Musiques traditionnelles, chants et percussions.",
    economy: "Agriculture, pêche, ressource minières (diamant), reconstruction et développement.",
    politics: "Période de recontruction après conflits, gouvernance en consolidation.",
    funfact: "Freetown a été un point important pour la diaspora et l'histoire des esclaves affranchis."
  },
  {
    name: "Togo",
    flag: "image/togo1.png",
    photo: "image/togo2.jpeg",
    capital: "Lomé",
    capitalPhoto: "image/togo3.jpeg",
    independence: "27 avril 1960",
    population: "8 millions d'habitants",
    languages: ["Français", "Ewé", "Kabyè" ],
    monuments: ["Koutammakou (site culturel)", "Monuments coloniaux et plages de Lomé"],
    monumentPhoto:"",
    culture: "Artisanat très développé, marchés colorés, danses traditionnelles et rites culturels.",
    gastronomy: "Akumè, fufu, sauces locales, plats à base d'igname et de poisson.",
    music: "Highlife, musiques traditionnelles, artistes contemporains infkuens en région",
    economy: "Agriculture, pêche, tourisme, commerce au port d Lomé, phosphates; petite industrie.",
    politics: "République avec scène politique active et débats sur réformes",
    funfact: "Togo est connu pour ses marchés animés et son artisanat traditionnel."
  }

  
  
  // ...ajoute les autres pays
];